### ISSUE TITLE
Iniquity won't start

### ISSUE THREAD

**Issue by IRoN-cP** [iniquitybbs/iniquity#5]
Hello BBS'ers

I wrote an Email but dont get an Answer .. so i try it again this way ...

I Install Iniquity like the Install Doc on different Systems ( PI, Odroid, BananaPI, Tinkerboard and PC ) and i try it with different Distributions .. i have all time the same Problem..

The Problem is .. if i type iniquity the server starts and give no Errors .. if i login in via Telnet i get the Message on my server ,, Someone connected to the system .. and on the client i call i get the Loading Screen .. thats all ... i really hope samone can help me .. 

The Installation of Enigma-BBS on all Systems runs Perfect .. 

I dont know if it important .. but i think the iqpkg not working .. the Install doc tell i have to call  iqpkg install eternity ..  but i only get the Iniquity ASCII and iqpkg - The Iniquity BBS Package Manager. 
Its every time the same message i can type iqpkg install bullshit .. its the same .. 

Please help me .. 

Greets IRoN

**Comment by IRoN-cP** [comment]
Hey Guyz .. 

26 Days ago i opend this issue and no one has an idea ?
Please help me .. i want run this nice BBS again!!!!

**Comment by ispyhumanfly** [comment]
Hi @IRoN-cP, I wanted to apologize for not responding to your emails, I think they just got buried in my inbox and they slipped past me. Another round of development is about to kick off with respect to this project. @lmanuel and @christianvozar and I will be meeting soon to discuss some of our next steps. 

I'll say now that what you're running into is pretty much where this project sits at present. Right now one cannot actually run and configure a BBS, we just have some of the underlying mechanisms in place for that. Initialize an iniquity bbs, configure the services with an ini, and, us iqpkg to browse  bbs modules that could be used to develop your bbs. 

So, in essence, as of this writing, you are using Iniquity BBS to the extend that it could be used. I'm actually pleased that it runs on all of the platforms you tested on that's very encouraging to our architecture thus far. 

Enigma BBS is a fantastic solution for you right now, as it is fully functional. NuSkooler, who is its author, also advises this project here from time to time. 

In closing, if you're looking to run a BBS "now", I highly recommend Enigma, Mystic, or Synchronet. And there are many others... 

If you'd like to stay engaged with our efforts here at the Iniquity project, please do, because our goal is to truly make the next generation BBS platform, inline with what NuSkooler is doing with Enigma.
